spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true

  datasource:
    url: jdbc:h2:mem:lottery

management:
  endpoints:
    web:
      exposure:
        include: info, health, shutdown
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

app:
  version: 0.0.1