spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:h2:file:~/h2/lottery

management:
  endpoints:
    web:
      exposure:
        include: info, health, shutdown
      base-path: /api
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

app:
  version: 0.0.1